DROP TABLE IF EXISTS service_order_part CASCADE;
DROP TABLE IF EXISTS parts_delivery_item CASCADE;
DROP TABLE IF EXISTS service_order_work CASCADE;
DROP TABLE IF EXISTS car_sale_payment CASCADE;
DROP TABLE IF EXISTS parts_delivery CASCADE;
DROP TABLE IF EXISTS service_order CASCADE;
DROP TABLE IF EXISTS car_sale CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS employee CASCADE;
DROP TABLE IF EXISTS spare_part CASCADE;
DROP TABLE IF EXISTS car_model CASCADE;
DROP TABLE IF EXISTS supplier CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS service_type CASCADE;
DROP TABLE IF EXISTS position CASCADE;
DROP TABLE IF EXISTS parts_manufactures CASCADE;
DROP TABLE IF EXISTS car_brand CASCADE;
DROP TABLE IF EXISTS status CASCADE;

DROP TYPE IF EXISTS fio_type CASCADE;


CREATE TYPE fio_type AS (
    last_name VARCHAR(50),
    first_name VARCHAR(50),
    middle_name VARCHAR(50)
);


COMMENT ON TYPE fio_type IS 'Составной пользовательский тип для ФИО физических лиц';



CREATE TABLE status (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(50) NOT NULL UNIQUE CONSTRAINT chk_status_name CHECK (length(trim(name)) >= 3)
);


CREATE TABLE car_brand (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE CONSTRAINT chk_brand_name CHECK (length(trim(name)) >= 2),
    country varchar(100) NOT NULL CONSTRAINT chk_brand_country CHECK (country ~ '^[А-Яа-яA-Za-z\s-]+$')
);


CREATE TABLE parts_manufactures (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL UNIQUE CONSTRAINT chk_manuf_name CHECK (length(trim(name)) >= 2),
    country varchar(100) NOT NULL CONSTRAINT chk_manuf_country CHECK (country ~ '^[А-Яа-яA-Za-z\s-]+$')
);


CREATE TABLE position (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE CONSTRAINT chk_position_name CHECK (length(trim(name)) >= 3)
);


CREATE TABLE service_type (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(250) NOT NULL UNIQUE CONSTRAINT chk_service_name CHECK (length(trim(name)) >= 3),
    price numeric(10, 2) NOT NULL CONSTRAINT chk_service_price CHECK (price > 0)
);


CREATE TABLE client (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio fio_type NOT NULL,
    phone varchar(20) NOT NULL UNIQUE CONSTRAINT chk_client_phone CHECK (phone ~ '^[0-9]{11}$'), -- Ровно 11 цифр
    email varchar(100) NOT NULL UNIQUE CONSTRAINT chk_client_email CHECK (email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'), -- Проверка на @
    birth_date date NOT NULL CONSTRAINT chk_client_birth CHECK (birth_date < CURRENT_DATE - INTERVAL '16 years'), -- Клиент должен быть старше 16 лет
    
    -- Ограничение на уровне таблицы для проверки внутренней структуры составного типа
    CONSTRAINT chk_client_fio_fields CHECK (
        length(trim((fio).last_name)) >= 2 AND 
        length(trim((fio).first_name)) >= 2
    )
);


CREATE TABLE supplier (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(150) NOT NULL CONSTRAINT chk_supplier_name CHECK (length(trim(name)) >= 2),
    phone varchar(20) NOT NULL UNIQUE CONSTRAINT chk_supplier_phone CHECK (phone ~ '^[0-9]{11}$'),
    email varchar(100) NOT NULL UNIQUE CONSTRAINT chk_supplier_email CHECK (email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'),
    adress varchar(300) NOT NULL CONSTRAINT chk_supplier_address CHECK (length(trim(adress)) >= 10)
);

CREATE TABLE car_model (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id bigint NOT NULL,
    name varchar(100) NOT NULL CONSTRAINT chk_model_name CHECK (length(trim(name)) >= 1),
    body_type varchar(50) NOT NULL CONSTRAINT chk_body_type CHECK (body_type IN ('Седан', 'Хэтчбек', 'Универсал', 'Внедорожник', 'Купе', 'Минивэн')),
    class varchar(10) NOT NULL CONSTRAINT chk_model_class CHECK (class IN ('A', 'B', 'C', 'D', 'E', 'F', 'S', 'M', 'J')),
    
    CONSTRAINT car_model_brand_fk FOREIGN KEY (brand_id) REFERENCES car_brand (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE spare_part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_id bigint NOT NULL,
    parts_number varchar(100) NOT NULL UNIQUE CONSTRAINT chk_part_number CHECK (length(trim(parts_number)) >= 3),
    name varchar(250) NOT NULL CONSTRAINT chk_part_name CHECK (length(trim(name)) >= 2),
    purchase_price numeric(10, 2) NOT NULL CONSTRAINT chk_part_purch_price CHECK (purchase_price > 0),
    sale_price numeric(10, 2) NOT NULL CONSTRAINT chk_part_sale_price CHECK (sale_price > 0),
    quantity integer NOT NULL DEFAULT 0 CONSTRAINT chk_part_qty CHECK (quantity >= 0),
    
    CONSTRAINT chk_part_prices_logic CHECK (sale_price >= purchase_price), -- Бизнес-правило: розница не ниже закупки
    CONSTRAINT spare_part_manufacturer_fk FOREIGN KEY (manufacturer_id) REFERENCES parts_manufactures (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE employee (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio fio_type NOT NULL,
    position_id bigint NOT NULL,
    phone varchar(20) NOT NULL UNIQUE CONSTRAINT chk_emp_phone CHECK (phone ~ '^[0-9]{11}$'),
    email varchar(100) NOT NULL UNIQUE CONSTRAINT chk_emp_email CHECK (email ~ '^[A-Za-z0-9._%-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$'),
    password varchar(255) NOT NULL CONSTRAINT chk_emp_pwd CHECK (length(password) >= 6),
    hierarchy_level varchar(30) DEFAULT 'Сотрудник',
    hire_date date NOT NULL DEFAULT CURRENT_DATE CONSTRAINT chk_emp_hire_date CHECK (hire_date <= CURRENT_DATE),
    
    CONSTRAINT chk_emp_fio_fields CHECK (
        length(trim((fio).last_name)) >= 2 AND 
        length(trim((fio).first_name)) >= 2
    ),
    CONSTRAINT employee_position_fk FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE car (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    VIN char(17) NOT NULL UNIQUE CONSTRAINT chk_car_vin CHECK (VIN ~ '^[A-HJ-NPR-Z0-9]{17}$'), -- Стандарт VIN без символов I, O, Q
    model_id bigint NOT NULL,
    year smallint NOT NULL CONSTRAINT chk_car_year CHECK (year >= 1990 AND year <= EXTRACT(YEAR FROM CURRENT_DATE)),
    color varchar(50) NOT NULL,
    mileage int NOT NULL DEFAULT 0 CONSTRAINT chk_car_mileage CHECK (mileage >= 0),
    purchase_price numeric(12, 2) NOT NULL CONSTRAINT chk_car_purch_price CHECK (purchase_price > 0),
    sale_price numeric(12, 2) NOT NULL CONSTRAINT chk_car_sale_price CHECK (sale_price > 0),
    status varchar(50) NOT NULL DEFAULT 'Доступен' CONSTRAINT chk_car_status CHECK (status IN ('Доступен', 'В резерве', 'Продан', 'На обслуживании')),
    
    CONSTRAINT chk_car_prices_logic CHECK (sale_price >= purchase_price),
    CONSTRAINT car_model_fk FOREIGN KEY (model_id) REFERENCES car_model (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE car_sale (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_data date NOT NULL DEFAULT CURRENT_DATE CONSTRAINT chk_sale_date CHECK (sale_data <= CURRENT_DATE),
    car_id bigint NOT NULL UNIQUE,
    client_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    total_amount numeric(12, 2) NOT NULL CONSTRAINT chk_sale_total CHECK (total_amount > 0),
    
    CONSTRAINT car_sale_car_fk FOREIGN KEY (car_id) REFERENCES car (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT car_sale_client_fk FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT car_sale_employee_fk FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE service_order (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_data date NOT NULL DEFAULT CURRENT_DATE CONSTRAINT chk_order_date CHECK (order_data <= CURRENT_DATE),
    car_id bigint NOT NULL,
    client_id bigint NOT NULL,
    employee_id bigint NOT NULL,
    status bigint NOT NULL,
    
    CONSTRAINT service_order_car_fk FOREIGN KEY (car_id) REFERENCES car (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT service_order_client_fk FOREIGN KEY (client_id) REFERENCES client (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT service_order_employee_fk FOREIGN KEY (employee_id) REFERENCES employee (id) ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT service_order_status_fk FOREIGN KEY (status) REFERENCES status (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE parts_delivery (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_date date NOT NULL DEFAULT CURRENT_DATE CONSTRAINT chk_delivery_date CHECK (delivery_date <= CURRENT_DATE),
    supplier_id bigint NOT NULL,
    total_amount numeric(12, 2) NOT NULL DEFAULT 0 CONSTRAINT chk_delivery_total CHECK (total_amount >= 0),
    
    CONSTRAINT parts_delivery_supplier_fk FOREIGN KEY (supplier_id) REFERENCES supplier (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE car_sale_payment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id bigint NOT NULL,
    payment_type varchar(50) NOT NULL CONSTRAINT chk_payment_type CHECK (payment_type IN ('Наличные', 'Безналичный расчет', 'Кредит', 'Трейд-ин')),
    amount numeric(12, 2) NOT NULL CONSTRAINT chk_payment_amount CHECK (amount > 0),
    
    CONSTRAINT payment_sale_fk FOREIGN KEY (sale_id) REFERENCES car_sale (id) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE service_order_work (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id bigint NOT NULL,
    service_type_id bigint NOT NULL,
    hours numeric(5, 2) NOT NULL CONSTRAINT chk_work_hours CHECK (hours > 0),
    price numeric(10, 2) NOT NULL CONSTRAINT chk_work_price CHECK (price >= 0),
    
    CONSTRAINT work_order_fk FOREIGN KEY (service_order_id) REFERENCES service_order (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT work_type_fk FOREIGN KEY (service_type_id) REFERENCES service_type (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE parts_delivery_item (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    delivery_id bigint NOT NULL,
    spare_part_id bigint NOT NULL,
    quanitity integer NOT NULL DEFAULT 1 CONSTRAINT chk_deliv_item_qty CHECK (quanitity > 0),
    price numeric(10, 2) NOT NULL CONSTRAINT chk_deliv_item_price CHECK (price > 0),
    
    CONSTRAINT item_delivery_fk FOREIGN KEY (delivery_id) REFERENCES parts_delivery (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT item_spare_part_fk FOREIGN KEY (spare_part_id) REFERENCES spare_part (id) ON DELETE RESTRICT ON UPDATE CASCADE
);


CREATE TABLE service_order_part (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_order_id bigint NOT NULL,
    spare_part_id bigint NOT NULL,
    quantity integer NOT NULL DEFAULT 1 CONSTRAINT chk_order_part_qty CHECK (quantity > 0),
    price numeric(10, 2) NOT NULL CONSTRAINT chk_order_part_price CHECK (price >= 0),
    
    CONSTRAINT part_order_fk FOREIGN KEY (service_order_id) REFERENCES service_order (id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT part_spare_part_fk FOREIGN KEY (spare_part_id) REFERENCES spare_part (id) ON DELETE RESTRICT ON UPDATE CASCADE
);



COMMENT ON TABLE client IS 'Информация о клиентах автосалона и сервисного центра';
COMMENT ON COLUMN client.id IS 'Суррогатный первичный ключ клиента';
COMMENT ON COLUMN client.phone IS 'Уникальный контактный телефон клиента (11 цифр)';
COMMENT ON COLUMN client.fio IS 'ФИО клиента в виде составной структуры (fio_type)';

COMMENT ON TABLE car IS 'Реестр автомобилей на складе автосалона и обслуживаемых в сервисе';
COMMENT ON COLUMN car.VIN IS 'Уникальный 17-значный международный идентификационный код ТС';
COMMENT ON COLUMN car.status IS 'Статус коммерческой доступности автомобиля';

COMMENT ON TABLE car_sale IS 'Регистрация фактов продажи автомобилей клиентам';
COMMENT ON COLUMN car_sale.total_amount IS 'Итоговая сумма по договору купли-продажи';

COMMENT ON TABLE service_order IS 'Заказ-наряды на выполнение ремонтных работ и обслуживание';
COMMENT ON COLUMN service_order.status IS 'Ссылка на текущий статус выполнения заказа';

COMMENT ON TABLE service_order_work IS 'Спецификация выполненных работ в рамках заказ-наряда';
COMMENT ON COLUMN service_order_work.hours IS 'Количество фактически затраченных нормо-часов';

COMMENT ON TABLE employee IS 'Учетные карточки штатных сотрудников компании';
COMMENT ON COLUMN employee.fio IS 'ФИО сотрудника в виде составной структуры (fio_type)';
